version: 2.1

jobs:
  build-geth:
    docker:
      - image: cimg/go:1.19
    resource_class: large
    steps:
      - checkout
      - run:
          command: go run build/ci.go install
  unit-test:
    resource_class: large
    docker:
      - image: cimg/go:1.19
    steps:
      - checkout
      - run:
          command: |
            curl -L https://foundry.paradigm.xyz | SHELL=/usr/bin/bash bash
            ~/.foundry/bin/foundryup
      - run:
          command: make geth
      - run:
          command: PATH="~/.foundry/bin:${PATH}" e2e_test/run_all_tests.sh
      - run:
          command: go run build/ci.go test
  lint-geth:
    resource_class: medium
    docker:
      - image: cimg/go:1.19
    steps:
      - checkout
      - run:
          command: go run build/ci.go lint


workflows:
  main:
    jobs:
      - build-geth:
          name: Build geth
      - unit-test:
          name: Run unit tests for geth
      - lint-geth:
          name: Run linter over geth
